# @package _global_

hsdp:
  enabled: true
  shard_group_size: 2
  sharding_strategy: HYBRID_SHARD
  sync_module_states: true
  limit_all_gathers: true
  forward_prefetch: false
  use_orig_params: true
  cpu_offload: false

fsdp_plugin:
  _target_: accelerate.FullyShardedDataParallelPlugin
  fsdp_version: 1
  auto_wrap_policy: no_wrap
  reshard_after_forward: HYBRID_SHARD
  state_dict_type: FULL_STATE_DICT
  use_orig_params: true
  sync_module_states: true
  limit_all_gathers: true
  cpu_offload: false
  cpu_ram_efficient_loading: false
  activation_checkpointing: false
