# @package _global_

trainer: trainers.pi3_trainer.Pi3Trainer

train:
  image_num_range: [2, 24]     # hres
  max_img_per_gpu: 48             # hres

  # low resolution
  resolution: 
    - [224, 224]

model:
  ckpt: "outputs/pi3_lowres_Illumination/ckpts/best_model/model.safetensors" # <path-to-your-pretrain-checkpoint>